### PR TITLE
Expanded missed API feature relating to the CreateEmbed API call

### PR DESCRIPTION
**Pull request by Flutterlice**
So i was making a bot that plays Shogi via sending image of the board inside of an embed and found out that your amazing library is missing following API feature completely:
https://discordapp.com/developers/docs/resources/channel#create-message-using-attachments-within-embeds
This API part states that if you send file in a multipart body alongside with json request you can use image you uploaded inside of your embed by addressing it via "attachment://image.png". I am not sure about your vision for exposed functions in this library (E.g. should this function be a separate kind of request like i made it be in this PR, or should it be an option inside of an CreateEmbed request), so feel free to point me in the right direction.

### CODE REVIEW

**Comment by aquarial** [comment]
Thanks for pushing the limits of the library and opening an issue/pull!

I'd like the EmbedWFile to be an option of the `CreateMessageEmbed`. See the `Embed`/`SubEmbed` ADTs. I admit they are a real mess right now, at some point I should rewrite `SubEmbed` completely. 

Ideally the api would look something like the following. 

```haskell

data Embed  = Embed {
           embedTitle :: Maybe T.Text,
           --- .. other fields ...
           embedFields :: [SubEmbed]
}

data SubEmbed = SubEmbed {
   subEmbedThumbnail :: Maybe EmbedImage
   subEmbedImage  :: Maybe EmbedImage
  -- .. other fields ..
   subEmbedAuthor :: Maybe SubEmbedAuthor
}

 -- https://discordapp.com/developers/docs/resources/channel#embed-object-embed-author-structure
data SubEmbedAuthor = SubEmbedAuthor {
   authorName :: T.Text
   authorIcon :: EmbedImage
}

data EmbedImage = EmbedImageUrl T.Text | EmbedImageContents ByteString

**Comment by Flutterlice** [comment]
What's the point of creating Record instead of an algebraic type for SubEmbed type? Since by the logic of embedFields field in Embed type being list of different SubEmbeds wouldn't it be better to leave SubEmbed as it is right now in code of your library? (E.g. 

`data SubEmbed =  Thumbnail | Video | Image | Provider | etc etc` 

and represent Image's and Thumbnail's fields as a general EmbedImage type that can be either EmbedImageUrl or EmbedImageContents?

**Comment by aquarial** [comment]
It's a legibility trade-off. SubEmbed author has [4 Text fields](https://discordapp.com/developers/docs/resources/channel#embed-object-embed-author-structure): name, url, icon_url, proxy_url (??). Leads to `Author T.Text T.Text T.Text T.Text`. Maybe that ambiguity is having instead of some more records. 

I spoke too soon on the "ideal" interface, there's still some design decisions. I know at the SubEmbed options are bad names: `Image` and `Field` are too common of names. Should be `SubEmbedImage` or so.

**Comment by Flutterlice** [comment]
Alright, i guess it is too early to think about implementing different image upload styles (url or direct upload) since there's no solid solution for all types that are going to be used. Meanwhile i'll just use my own ad-hock solution in my bot, but i am looking forward for this feature to be implemented in the upstream!

**Comment by aquarial** [comment]
After some digging, I found that discord bots can't set a lot of the fields that appear in the Embed. 

New API: `CreateEmbed` has all the fields a bot can set, `Embed` contains all the data discord sends us, and `createEmbed :: CreateEmbed -> Embed` converts a user provided value to upload.

```haskell


data CreateEmbed = CreateEmbed
  { createEmbedAuthorName  :: T.Text
  , createEmbedAuthorUrl   :: T.Text
  , createEmbedAuthorIcon  :: Maybe CreateEmbedImage
  , createEmbedTitle       :: T.Text
  , createEmbedUrl         :: T.Text
  , createEmbedThumbnail   :: Maybe CreateEmbedImage
  , createEmbedDescription :: T.Text
  , createEmbedFields      :: [EmbedField]
  , createEmbedImage       :: Maybe CreateEmbedImage
  , createEmbedFooterText  :: T.Text
  , createEmbedFooterIcon  :: Maybe CreateEmbedImage
-- TODO
--, createEmbedColor       :: Maybe T.Text
--, createEmbedTimestamp   :: Maybe UTCTime
  } deriving (Show, Eq, Ord)

data CreateEmbedImage = CreateEmbedImageUrl T.Text
                   -- TODO
                   -- | CreateEmbedImageUpload B.ByteString
  deriving (Show, Eq, Ord)
```

`Default` instance allows setting partial fields.

Todo: support uploading, colors (what type?), timestamps

```haskell
_ <- restCall dis (R.CreateMessageEmbed (channelId c) "" $
           def { createEmbedAuthorName  = "Aquarial"
               , createEmbedAuthorUrl   = "https://github.com/aquarial"
               , createEmbedAuthorIcon  = Just $ CreateEmbedImageUrl "https://long_url"
               , createEmbedTitle = "Ping Pong Bot"
               , createEmbedUrl  = "https://github.com/aquarial/discord-haskell"
               , createEmbedThumbnail  = Just $ CreateEmbedImageUrl "https://long_url"
               , createEmbedDescription  = "Replies to 'ping' with 'Pong!'"
               , createEmbedFields = [ EmbedField "PING" "Pong!" (Just False)
                                     , EmbedField "Pinged" "Pong!" (Just True)
                                     , EmbedField "pinGer" "Pong!" (Just True)
                                     , EmbedField "ping here" "Pong!" (Just True)
                                     ]
               , createEmbedImage  = Just $ CreateEmbedImageUrl "https://long_url"
               , createEmbedFooterText = "PING THAT PONG MY FRIEND"
               , createEmbedFooterIcon  = Just $ CreateEmbedImageUrl "https://long_url"
               }
       )

```

pingpong

**Comment by aquarial** [comment]
I won't merge this specific pull-request because I like the more general Embed api. I'm going to try to finish upload image Embed tonight.

**Comment by aquarial** [comment]
This part of the pull request has been really helpful, I didn't know how about `payload_json`!

```haskell
  (CreateMessageEmbedWFile chan msg embed fileName file) ->
      let content = ["content" .= msg] <> maybeEmbed (Just embed)
          partJson = partLBS "payload_json" $ encode $ toJSON $ object content 
          partFile = partFileRequestBody "file" (T.unpack fileName) $ RequestBodyBS file
          body = R.reqBodyMultipart [partJson, partFile]
      in Post (channels // chan /: "messages") body mempty
```

**Comment by aquarial** [comment]
Can now upload images! I don't allow the user to set the names.

**Pull request closed without merging**
