### PR TITLE
Refactored to Monad Stack

### PR DESCRIPTION
**Pull request by elikoga**
Refactored `DiscordHandle -> IO a` to `DiscordHandler a` Monad Transformer Stack

I oriented myself around this guide: https://thoughtbot.com/blog/refactoring-to-a-monad-transformer-stack

This was mentioned in #34

### CODE REVIEW

**Comment by aquarial** [comment]
I wasn't sure about the mondad stack stuff,  but I noticed https://github.com/aquarial/discord-haskell/issues/34 has 4 thumbs up, seems like a popular request!

I looked over this pr and the changes seem reasonable. I'll merge this, and get up to speed on this stuff. I'll update the Readme and examples on Sunday when I get back home

**Comment by aquarial** [comment]
there's a merge conflict. I can't fix it from mobile

**Comment by elikoga** [comment]
I think the merge conflict should be resolved now

**Comment by aquarial** [comment]
Alright

**Pull request merged**
