### PR TITLE
Draft: Sharding

### PR DESCRIPTION
**Pull request by aquarial**
Looking into implementation.

Current plan is to provide two sharding strategies: (1) automatic handling for separate websocket connections as default, (2) configuration for selecting specific sharding at startup. 

Manual specification of sharding allows horizontal scaling across multiple computers.

### CODE REVIEW

**Comment by aquarial** [comment]
Current status of this PR: still a draft.

Right now this branch can auto-start shards based on discord's recommendation, and also has UI to manually select sharding.

What it lacks: connecting to the shards in the first place is much slower than optimal. The shards each independently try to reconnect (re-identify) which if they happen at once would break the rate limit.

Where it's going: the PR needs a shard manager thread that coordinates the connecting and reconnecting of shards, similar to the REST ratelimiter in this repo.

**Comment by aquarial** [comment]
Finished simple implementation, opening a PR

**Comment by chrissound** [comment]
It seems like some code is no longer present on the latest master branch. The sharding docs or `RunDiscordOpts.discordSharding` for example. 

Does anyone know if the library currently supports sharding or not?

**Comment by aquarial** [comment]
cc @yutotakano 

I've just pushed the changes i was working on in [the sharding-rework branch](https://github.com/discord-haskell/discord-haskell/compare/sharding-rework), which had some code, some notes and some docs

I had gotten a janky MVar based solution up so that the shards that were started would reconnect over time, using concurrency to space out the connections

I was trying to implement some advanced features like allowing the user to dynamically change the number of shards and re-connect them during run-time, and was getting frustrated with Haskell's concurrency. TBh was getting less interested in Haskell in general 😅 . 

So here's a minimal viable implementation if you'd like to take a look at sharding soon

**Comment by yutotakano** [comment]
@aquarial Thanks! Took a peek at the branch, and gosh I had underestimated how complex sharding would be! Thank you so much for the work so far, looks very useful. Hopefully over the next few weeks (while I have summer holiday) I should be able to refine the user-facing API and maybe take a stab at some of the advanced things you were trying to do. Will open a new PR once ready.

> was getting frustrated with Haskell's concurrency. TBh was getting less interested in Haskell in general 😅 .

I get you, the concurrency primitives are very verbose and sometimes it feels like there's a lot of unchecked async logic that defeats the safety aspect of Haskell (especially when there are multiple threads each spawning each other and you have to synchronise events/state back and forth...). One of the reasons why my interest in the language fluctuates too. Anyway, when you get a surge of interest in Haskell again, I'd love to see you active again :) Until then, leave sharding to me and I'll see if I can get it release-ready.

**Pull request closed without merging**
